[features]
seeds = false
skip-lint = false

[programs.localnet]
delta_neutral_vault = "35ZfJRQpQmbogZ5SqEYh7mDeyWJBM7XhD6NV4TbfgFZp"

[programs.devnet]
delta_neutral_vault = "35ZfJRQpQmbogZ5SqEYh7mDeyWJBM7XhD6NV4TbfgFZp"

[programs.mainnet]
delta_neutral_vault = "35ZfJRQpQmbogZ5SqEYh7mDeyWJBM7XhD6NV4TbfgFZp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "ts-node scripts/deploy.ts"
setup = "ts-node scripts/setup.ts"
